language: 
  - objective-c
osx_image: 
  - xcode9.4
script:
  - xcodebuild test -workspace 'HDWalletKit.xcworkspace' -scheme 'HDWalletKit_Tests' -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.4'
after_success:
- bash <(curl -s https://codecov.io/bash)
branches:
  only:
  - feature/auto-deploy
rvm:
- 2.0.0
install:
- git config --global user.email "pavlo.bojkoo@gmail.com"
- git config --global user.name "Pavlo Boiko"
- pod repo add master ${GH_TOKEN}@github.com/CocoaPods/Specs.git
- pod repo add essentia ${GH_TOKEN}@github.com/ess-cocoapodspec/HDWallet.git
- pod setup
- pod env
- pod trunk register pavlo.bojkoo@gmail.com 'Pavlo Boiko' --description="God iOS"
script:
- xcodebuild test -workspace 'HDWalletKit.xcworkspace' -scheme 'HDWalletKit_Tests' -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.4'
- pod trunk push HDWalletKit.podspec
- pod repo push essentia  HDWalletKit.podspec
env:
  global:
    secure: KE5x2fZOOybk/jLluQaHZNhZ5AEnldx/NTQWupSvzd3Cvc0PP01UfYpCOg/qqvO2xNX066B9K3CaAFLEo1aqKwISnBSMNafNRntlK4A1i5eoKJHaUh2wg8ct6g4zxX8nAE2IriOedvTwTU4oo1gGxUjWc/W1HSEm4pCDw/+QdwSiQ4KMhNHrvxvAH5qXGQdZoIVmUDSvY3M5uvI+wlIdBGII4dgjefBburYZh6MTm/ikT/47np/jJ5kz9Ul6SkYMP6nRW4W/ZZfzBEO9G2N75/9ZTLwWKE3nIG8dPc9Wp8G1AWxIHVG/oQItYVmzdUNdnklJIL6PNGhXtC0eE05hK1lYr4BrNfbfL9HKvBX+iUjAx3Z4t+sff1/PWD484GWV+jQtBu8W9DOvOKHREuakmb8CJEPUaCAMdocHdgwFrFgYRWxiOIngL5/uqPEHqtrFWN84kcOCjDodw8qr35cI4kgYCrcs9ZKjwr/IHkj9S7VzTyhPuRTMHfhxUUV24RsK++jBajegw6MAfrCNQLcXCGJbCJk9JddDmGQqHqnuPMBtQNfRxgs1Bl3xmLuLljmgTATrqDkTpyNEQeDnpehJkKTTa25DRjUW1yZE+3XE/TWczRslFYnre8B2fcdID5H028l29jynRY7qdJuNJ2bqrLI8piTkY/aCeQscW8f2uA8=
